-- vincents_online_shop Database

DROP TABLE IF EXISTS INVENTORY;
DROP TABLE IF EXISTS TRANSACTION_DETAILS;
DROP TABLE IF EXISTS CUSTOMER_DETAILS;
DROP TABLE IF EXISTS EMPLOYEE;
DROP TABLE IF EXISTS SHOP;
DROP TABLE IF EXISTS CATEGORY;
DROP TABLE IF EXISTS SUB_CATEGORY;
DROP TABLE IF EXISTS SEASON;

CREATE TABLE INVENTORY (
    ITEM_ID    INT(10) NOT NULL,
	ITEM_NAME    VARCHAR(35)  CHARACTER SET UTF8MB4 NOT NULL,
	ITEM_DESCRIPTION  VARCHAR(150),
	SUB_CATEGORY_ID    INT(5),
	PRIZE    DECIMAL(40),
    SIZE    VARCHAR(50),
    PICTURE    BLOB,
    IN_STOCK_DATE   DATE,
    ITEM_STATUS    VARCHAR(50),
    SHOP_ID    INT(5),
    SEASON_ID   INT(5)
    PRIMARY KEY (ITEM_ID),
	FOREIGN KEY (SHOP_ID) REFERENCES SHOP (SHOP_ID),
	FOREIGN KEY (SEASON_ID) REFERENCES SEASON (SEASON_ID));

CREATE TABLE SEASON (
    SEASON_ID   INT(5),
    SEASON_NAME   VARCHAR(35) CHARACTER SET UTF8MB4 NOT NULL,
    PRIMARY KEY (SEASON_ID));

CREATE TABLE CATEGORY (
    CATEGORY_ID   INT(5),
    CATEGORY_NAME   VARCHAR(35) CHARACTER SET UTF8MB4 NOT NULL,
    PRIMARY KEY (CATEGORY_ID));

CREATE TABLE SUB_CATEGORY (
    SUB_CATEGORY_ID   INT(5),
    SUB_CATEGORY_NAME   VARCHAR(35) CHARACTER SET UTF8MB4 NOT NULL,
    CATEGORY_ID    INT(5),
    PRIMARY KEY (SUB_CATEGORY_ID),
	FOREIGN KEY (CATEGORY_ID) REFERENCES CATEGORY (CATEGORY_ID));

CREATE TABLE SHOP (
    SHOP_ID    INT(5),
    SHOP_NAME    VARCHAR(35) CHARACTER SET UTF8MB4 NOT NULL,
    SHOP_OPENING_HOURS    VARCHAR(35),
    ADDRESS    VARCHAR (100),
    CONTACT_NUMBER   VARCHAR(35),
    EMPLOYEE_ID    INT(5),
    PRIMARY KEY (SHOP_ID),
    FOREIGN KEY (EMPLOYEE_ID) REFERENCES EMPLOYEE (EMPLOYEE_ID);

CREATE TABLE EMPLOYEE (
    EMPLOYEE_ID    INT(5),
    EMPLOYEE_NAME    VARCHAR(35) CHARACTER SET UTF8MB4 NOT NULL,
	CONTACT_NUMBER   VARCHAR(35),
    LAST_DAY    VARCHAR(8) NOT NULL,
    PRIMARY KEY (EMPLOYEE_ID);    
        
CREATE TABLE CUSTOMER_DETAILS (
    CUSTOMER_ID    INT(5),
    CUSTOMER_NAME    VARCHAR(35) CHARACTER SET UTF8MB4 NOT NULL,
    EMAIL    VARCHAR(35),
    MOBILE/TELEPHONE    VARCHAR(35),
    PRIMARY KEY (CUSTOMER_ID);
        
CREATE TABLE TRANSACTION_DETAILS (
    TRANSACTION_ID    INT(10),
    ITEM_ID    INT(5),
    SOLD_DATE    DATE,
    EMPLOYEE_ID    INT(5),
    SHOP_ID    INT(5),
    CUSTOMER_ID    INT(5),
    PRIMARY KEY (TRANSACTION_ID),
	FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER (CUSTOMER_ID),
	FOREIGN KEY (ITEM_ID) REFERENCES INVENTORY (ITEM_ID),
	FOREIGN KEY (EMPLOYEE_ID) REFERENCES EMPLOYEE (EMPLOYEE_ID)	);