-- vincents_online_shop Database

INSERT INTO INVENTORY (ITEM_ID, ITEM_NAME, ITEM_DESCRIPTION, SUB_CATEGORY_ID, PRIZE, SIZE, PICTURE, IN_STOCK_DATE, ITEM_STATUS, SHOP_ID, SEASON_ID) VALUES;

INSERT INTO SEASON (SEASON_ID, SEASON_NAME) VALUES;

INSERT INTO CATEGORY (CATEGORY_ID, CATEGORY_NAME) VALUES;

INSERT INTO SUB_CATEGORY (SUB_CATEGORY_ID, SUB_CATEGORY_NAME, CATEGORY_ID) VALUES;

INSERT INTO SHOP (SHOP_ID, SHOP_NAME, SHOP_OPENING_HOURS, ADDRESS, CONTACT_NUMBER, EMPLOYEE_ID) VALUES;

INSERT INTO EMPLOYEE (EMPLOYEE_ID, EMPLOYEE_NAME, CONTACT_NUMBER, LAST_DAY) VALUES;

INSERT INTO CUSTOMER_DETAILS (CUSTOMER_ID, CUSTOMER_NAME, EMAIL, MOBILE/TELEPHONE) VALUES;

INSERT INTO TRANSACTION_DETAILS (TRANSACTION_ID, ITEM_ID, SOLD_DATE, EMPLOYEE_ID, SHOP_ID, CUSTOMER_ID) VALUES;